# открывается файл /etc/systemd/zram-generator.conf
# ниже три образца
# типов сжатия несколько, lz4 почти что вообще не нагружает процессор, самый легкий и быстрый

[zram0]
zram-size = ram
compression-algorithm = lz4

[zram0]
zram-size = ram / 2
compression-algorithm = lz4

[zram0]
zram-size = 4G
compression-algorithm = lz4

# после выполнить команды:
# sudo systemctl daemon-reload
# sudo systemctl start /dev/zram0
# перезагрузить пк если изменения не вступили в силу

